/obj/structure/closet/wardrobe/mixed/PopulateContents()
	if(prob(40))
		new /obj/item/clothing/suit/jacket(src)
	if(prob(40))
		new /obj/item/clothing/suit/jacket(src)
	new /obj/item/clothing/under/polychromic/jumpsuit(src)
	new /obj/item/clothing/under/polychromic/jumpsuit(src)
	new /obj/item/clothing/under/polychromic/jumpsuit(src)
	new /obj/item/clothing/under/polychromic/shirt(src)
	new /obj/item/clothing/under/polychromic/shirt(src)
	new /obj/item/clothing/under/polychromic/shirt(src)
	new /obj/item/clothing/under/polychromic/kilt(src)
	new /obj/item/clothing/under/polychromic/kilt(src)
	new /obj/item/clothing/under/polychromic/kilt(src)
	new /obj/item/clothing/under/polychromic/skirt(src)
	new /obj/item/clothing/under/polychromic/skirt(src)
	new /obj/item/clothing/under/polychromic/skirt(src)
	new /obj/item/clothing/under/polychromic/shorts(src)
	new /obj/item/clothing/under/polychromic/shorts(src)
	new /obj/item/clothing/under/polychromic/shorts(src)
	new /obj/item/clothing/under/polychromic/shortpants/pantsu(src)
	new /obj/item/clothing/under/polychromic/shortpants/pantsu(src)
	new /obj/item/clothing/under/polychromic/shortpants/pantsu(src)
	new /obj/item/clothing/under/polychromic/bulge(src)
	new /obj/item/clothing/under/polychromic/bulge(src)
	new /obj/item/clothing/under/polychromic/bulge(src)
	new /obj/item/clothing/under/polychromic/bikini(src)
	new /obj/item/clothing/under/polychromic/bikini(src)
	new /obj/item/clothing/under/polychromic/bikini(src)
	new /obj/item/clothing/under/polychromic/stripper(src)
	new /obj/item/clothing/under/polychromic/stripper(src)
	new /obj/item/clothing/under/polychromic/stripper(src)
	new /obj/item/clothing/under/polychromic/bottomless(src)
	new /obj/item/clothing/under/polychromic/bottomless(src)
	new /obj/item/clothing/under/polychromic/bottomless(src)
	new /obj/item/clothing/mask/bandana/red(src)
	new /obj/item/clothing/mask/bandana/red(src)
	new /obj/item/clothing/mask/bandana/blue(src)
	new /obj/item/clothing/mask/bandana/blue(src)
	new /obj/item/clothing/mask/bandana/gold(src)
	new /obj/item/clothing/mask/bandana/gold(src)
	new /obj/item/clothing/shoes/sneakers/black(src)
	new /obj/item/clothing/shoes/sneakers/brown(src)
	new /obj/item/clothing/shoes/sneakers/white(src)
	new /obj/item/clothing/suit/polychromic/kromajacket(src)
	new /obj/item/clothing/suit/polychromic/kromacrop(src)
	new /obj/item/clothing/under/polychromic/shortsbra(src)
	if(prob(30))
		new /obj/item/clothing/suit/hooded/wintercoat(src)
		new /obj/item/clothing/shoes/winterboots(src)
	return

/obj/structure/closet/wardrobe/curator/PopulateContents()
	..()
	new /obj/item/clothing/accessory/pocketprotector/full(src)
