#define ECONOMY_TYPE_ROOKIE		"Rookie"
#define ECONOMY_TYPE_DANGEROUS	"Dangerous"
#define ECONOMY_TYPE_COMMAND	"Command"

#define ECONOY_PRICE_DEFAULT		0
#define ECONOMY_PRICE_LOW			1
#define ECONOMY_PRICE_HIGH			2
#define ECONOMY_PRICE_EROTIC		3
#define ECONOMY_PRICE_EXPENSIVE		4
#define ECONOMY_PRICE_EXPENSIVE_AF	5
